# Wildcard labels

template: 'facelessuser:master-labels:labels.yml:master'

brace_expansion: true
minus_negate: false

rules:
  - labels: ['C: infrastructure']
    patterns: ['*|.github/**|!README.md']

  - labels: ['C: source']
    patterns: ['label_bot/**']

  - labels: ['C: docs']
    patterns: ['README.md']

  - labels: ['C: wip-labels']
    patterns: ['label_bot/wip_labels.py']

  - labels: ['C: triage-labels']
    patterns: ['label_bot/triage_labels.py']

  - labels: ['C: review-labels']
    patterns: ['label_bot/review_labels.py']

  - labels: ['C: wildcard-labels']
    patterns: ['label_bot/wildcard_labels.py']

  - labels: ['C: sync-labels']
    patterns: ['label_bot/sync_labels.py']

  - labels: ['C: lgtm-labels']
    patterns: ['label_bot/lgtm_labels.py']

  - labels: ['C: add-remove-labels']
    patterns: ['label_bot/add_remove_labels.py']

# Label management

ignores:
  - dependencies
  - security


labels:
- name: 'C: sync-labels'
  renamed: sync-labels
  color: subcategory
  description: Sync labels library.

- name: 'C: lgtm-labels'
  renamed: lgtm-labels
  color: subcategory
  description: LGTM labels library.

- name: 'C: add-remove-labels'
  renamed: add-remove-labels
  color: subcategory
  description: Add/remove labels library.

- name: 'C: wip-labels'
  renamed: wip-labels
  color: subcategory
  description: WIP labels library.

- name: 'C: triage-labels'
  renamed: triage-labels
  color: subcategory
  description: Triage label library.

- name: 'C: review-labels'
  renamed: review-labels
  color: subcategory
  description: Review label library.

- name: 'C: wildcard-labels'
  renamed: wildcard-labels
  color: subcategory
  description: Wildcard labels library.
